# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: teeohbee.github.io
email: teeohbee@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The trials and tribulations of a junior developer - making code, breaking
  code and hopefully in the process honing his craft. Perhaps.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://teeohbee.github.io" # the base hostname & protocol for your site
twitter_username: teeohbee
github_username:  teeohbee

# Build settings
markdown: kramdown

# Gem files
gems:
  - jemoji
